version: '3.7'
services:
  database:
    container_name: local-mysql
    image: mysql
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    cap_add:
      - SYS_NICE
volumes:
  mysql:

