spring:
  jpa:
    hibernate:
      ddl-auto: create

security:
  user:
    password: password

app:
  default:
    user: 'root'
    password: 'password'
    roles:
      admin: 'ADMIN'
      user: 'USER'