spring:
  jpa:
    hibernate:
      properties:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
app:
  url: http://localhost:8080