spring:
  jpa:
    hibernate:
      properties:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect

  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Drive

app:
  url: